- name: Read yaml file from the remote hosts
  hosts: all
  tasks:
    - name: Read yaml file from host
      ansible.builtin.command: cat /home/vagrant/slurp.yaml
      register: command_result

    - name: Print result
      ansible.builtin.debug:
        var: command_result

    - name: Load data into variable
      ansible.builtin.set_fact:
        my_var: "{{ command_result.stdout | from_yaml }}"

    - name: Print raw string
      ansible.builtin.debug:
        var: my_var.key0

